### ISSUE TITLE
all Values are strings?

### ISSUE THREAD

**Issue by kavink** [Accenture/waterfall-config#9]
All values are only String and List whereas type safe Config automatically will convert string to boolean or int to float etc.

Does the user of waterfall-config need to cast values explicitly instead of using HOCON ?

**Comment by sergiofgonzalez** [comment]
Hi @kavink ,
Yes, it only provides strings. Note that, at least for Java 8 where you don't have `var`, even the underlying library does not perform the casting for yourself: you are given variants of the get method that provide the specific type (e.g.  `getInt`, `getBytes`, `getDouble`...).

When designing the API we decided to keep it as simple and possible and return only strings.

Kind regards,
Sergio

**Comment by sergiofgonzalez** [comment]
closing the question thread.
